//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class catClavesMovimientos
    {
        public string ClaveMovimiento { get; set; }
        public string ClaveTen { get; set; }
        public string ClaveMovDescripcion { get; set; }
        public int ClaveMovimientoID { get; set; }
    }
}
