//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDivisas
    {
        public int ClaveDivisa { get; set; }
        public string Descripcion { get; set; }
        public string Abreviacion { get; set; }
        public Nullable<int> ClaveMonedaID { get; set; }
        public Nullable<int> ClaveCovaf { get; set; }
        public Nullable<int> DenBancoDI { get; set; }
        public Nullable<int> DenCompIDI { get; set; }
    }
}
