//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class catOperadoras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catOperadoras()
        {
            this.catRelUniNegOper = new HashSet<catRelUniNegOper>();
            this.catRelUsuOper = new HashSet<catRelUsuOper>();
            this.tblInventarioArchivos = new HashSet<tblInventarioArchivos>();
        }
    
        public int ClaveOperadoraID { get; set; }
        public string ClaveOperadora { get; set; }
        public Nullable<int> ClaveTipoOperadoraID { get; set; }
        public Nullable<int> ClaveProveedorID { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.Guid> UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual catProveedores catProveedores { get; set; }
        public virtual catTipoOperadora catTipoOperadora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catRelUniNegOper> catRelUniNegOper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catRelUsuOper> catRelUsuOper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventarioArchivos> tblInventarioArchivos { get; set; }
    }
}
