//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class catRelUniNegOper
    {
        public int ClaveUnidadNegocioOperadoraID { get; set; }
        public int ClaveUnidadNegocioID { get; set; }
        public int ClaveOperadoraID { get; set; }
    
        public virtual catOperadoras catOperadoras { get; set; }
        public virtual tblUnidadNegocio tblUnidadNegocio { get; set; }
    }
}
