//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEV_StagingEntities : DbContext
    {
        public DEV_StagingEntities()
            : base("name=DEV_StagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catClavesMovimientos> catClavesMovimientos { get; set; }
        public virtual DbSet<catOperadoras> catOperadoras { get; set; }
        public virtual DbSet<catProveedores> catProveedores { get; set; }
        public virtual DbSet<catRelUniNegOper> catRelUniNegOper { get; set; }
        public virtual DbSet<catRelUsuOper> catRelUsuOper { get; set; }
        public virtual DbSet<catTipoOperadora> catTipoOperadora { get; set; }
        public virtual DbSet<catTipoProveedor> catTipoProveedor { get; set; }
        public virtual DbSet<tblDiasFestivos> tblDiasFestivos { get; set; }
        public virtual DbSet<tblInventarioArchivos> tblInventarioArchivos { get; set; }
        public virtual DbSet<tblLogCarga> tblLogCarga { get; set; }
        public virtual DbSet<tblUnidadNegocio> tblUnidadNegocio { get; set; }
        public virtual DbSet<tblUsuarios> tblUsuarios { get; set; }
        public virtual DbSet<catDivisas> catDivisas { get; set; }
        public virtual DbSet<catFondos> catFondos { get; set; }
        public virtual DbSet<catFondos_Test> catFondos_Test { get; set; }
        public virtual DbSet<catFondoSeries> catFondoSeries { get; set; }
        public virtual DbSet<catPaises> catPaises { get; set; }
        public virtual DbSet<catTipoAIMSExcedentes> catTipoAIMSExcedentes { get; set; }
        public virtual DbSet<catTipoAmortCupones> catTipoAmortCupones { get; set; }
        public virtual DbSet<catTipoDEPBMX> catTipoDEPBMX { get; set; }
        public virtual DbSet<catTipoDividendos> catTipoDividendos { get; set; }
        public virtual DbSet<tblCargaCartera> tblCargaCartera { get; set; }
        public virtual DbSet<tblCargaDA> tblCargaDA { get; set; }
        public virtual DbSet<tblCargaMV> tblCargaMV { get; set; }
        public virtual DbSet<tblCargaVector> tblCargaVector { get; set; }
    }
}
