//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TCFix
    {
        public int TCFixID { get; set; }
        public Nullable<decimal> TCFix { get; set; }
        public Nullable<System.DateTime> FechaOperacion { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.Guid> UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
