//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCargaDA
    {
        public string Derecho { get; set; }
        public string Portafolio { get; set; }
        public string EmisoraSerie { get; set; }
        public int Posicion { get; set; }
        public double Precio { get; set; }
        public double ImporteBruto { get; set; }
        public int Impuesto { get; set; }
        public int PorcentajePosicion { get; set; }
        public System.DateTime Liquidacion { get; set; }
        public double ImporteInicialNeto { get; set; }
    }
}
