//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCargaVector
    {
        public string AreaID { get; set; }
        public string ClaveOperadoraID { get; set; }
        public string TipoReg { get; set; }
        public string TipoMercado { get; set; }
        public Nullable<System.DateTime> FechaOper { get; set; }
        public string TV { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public string PrecioSucio { get; set; }
        public string PrecioLimpio { get; set; }
        public string Interes { get; set; }
        public string CveProveedor { get; set; }
        public string TipoEnvio { get; set; }
        public string DiasxVencer { get; set; }
        public string TasaDescto { get; set; }
    }
}
