//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCargaMV
    {
        public string CveFondo { get; set; }
        public string CveMdo { get; set; }
        public string CveGpo { get; set; }
        public string CveInst { get; set; }
        public string Isin { get; set; }
        public string CveBmv { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public string FecOper { get; set; }
        public string FecLiq { get; set; }
        public string CveMov { get; set; }
        public string CveLiq { get; set; }
        public string CveTen { get; set; }
        public string CveCov { get; set; }
        public string MovCnbv { get; set; }
        public string CveProv { get; set; }
        public string Plazo { get; set; }
        public string Tasa { get; set; }
        public string Titulos { get; set; }
        public string Tcambio { get; set; }
        public string Pactado { get; set; }
        public string ImpBruto { get; set; }
        public string ImpInt { get; set; }
        public string ImpComs { get; set; }
        public string ImpIva { get; set; }
        public string ImpIsr { get; set; }
        public string Pais { get; set; }
        public string Moneda { get; set; }
        public string Hora { get; set; }
        public string TasaFv { get; set; }
        public string TasaRef { get; set; }
        public string Aforo { get; set; }
        public string FolFront { get; set; }
        public string CveBrok { get; set; }
        public string ComBrok { get; set; }
        public string IvaBrok { get; set; }
        public string PrecFdos { get; set; }
        public string MdoPrim { get; set; }
        public string MedioConc { get; set; }
        public string CtoUnit { get; set; }
    }
}
