//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCargaCartera
    {
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ClaveOperadoraID { get; set; }
        public string TipoInversion { get; set; }
        public string ClaveFondo { get; set; }
        public string ClaveSerie { get; set; }
        public string TV { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public Nullable<decimal> TitulosIniciales { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public string UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaOper { get; set; }
    }
}
