//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDE
    {
        public Nullable<System.DateTime> FechaOper { get; set; }
        public Nullable<int> CveFondo { get; set; }
        public string CveBmv { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public string PaisTrans { get; set; }
        public string MonedaTrans { get; set; }
        public Nullable<decimal> ImpMonOrig { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public string Pactado { get; set; }
        public string DivGrex { get; set; }
        public string IsrFecId { get; set; }
        public string IsrMonId { get; set; }
        public string IsrTcId { get; set; }
        public string IsrPactId { get; set; }
        public string IsrImpId { get; set; }
        public string IsrFecPro { get; set; }
        public string IsrMonPro { get; set; }
        public string IsrTcPro { get; set; }
        public string IsrPactPr { get; set; }
        public string IsrImpPro { get; set; }
        public int DEThroughID { get; set; }
    }
}
