//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDA
    {
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ClaveOperadoraID { get; set; }
        public string Derecho { get; set; }
        public string Portafolio { get; set; }
        public string TV { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public Nullable<double> Posicion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> ImporteBruto { get; set; }
        public Nullable<double> Impuesto { get; set; }
        public Nullable<double> PorcentajePosicion { get; set; }
        public Nullable<System.DateTime> Liquidacion { get; set; }
        public Nullable<double> ImporteInicialNeto { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.Guid> UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaOper { get; set; }
        public int DerechosAmortizacionesID { get; set; }
    }
}
