//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventarioArchivos
    {
        public int InventarioArchivos { get; set; }
        public Nullable<int> EtapaID { get; set; }
        public Nullable<int> UnidadDeNegocioID { get; set; }
        public string Proceso { get; set; }
        public string Archivo { get; set; }
        public string NombreArchivo { get; set; }
        public string Ruta { get; set; }
        public string Accion { get; set; }
        public string Regulatorio { get; set; }
        public string Requisitos { get; set; }
        public string Historico { get; set; }
        public string Interaccion { get; set; }
        public string Tamano { get; set; }
        public Nullable<int> EstatusCargaID { get; set; }
        public Nullable<int> ClaveOperadoraID { get; set; }
    
        public virtual catOperadoras catOperadoras { get; set; }
    }
}
