//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMV
    {
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ClaveOperadoraID { get; set; }
        public string CveFondo { get; set; }
        public string ClaveSerie { get; set; }
        public string TV { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public Nullable<int> Titulos { get; set; }
        public Nullable<int> CveMov { get; set; }
        public Nullable<double> ImpBruto { get; set; }
        public string Hora { get; set; }
        public Nullable<System.DateTime> FechaOper { get; set; }
        public Nullable<int> EstatusRegistroID { get; set; }
        public Nullable<System.Guid> UsuarioID { get; set; }
        public int MVThroughID { get; set; }
    }
}
