//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVector
    {
        public Nullable<System.DateTime> FechaOper { get; set; }
        public string TV { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public Nullable<double> PrecioLimpio { get; set; }
        public Nullable<double> Intereses { get; set; }
        public Nullable<double> PrecioSucio { get; set; }
        public int VectorThroughID { get; set; }
    }
}
