//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_ContableGaf
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCarteraPM
    {
        public int AreaID { get; set; }
        public int ClaveOperadoraID { get; set; }
        public string TV { get; set; }
        public string Emisora { get; set; }
        public string Serie { get; set; }
        public Nullable<int> CostoPP { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<int> Titulos { get; set; }
        public Nullable<double> ImporteCosto { get; set; }
        public Nullable<double> ImporteHoy { get; set; }
        public Nullable<double> PlusMin { get; set; }
        public Nullable<System.DateTime> FechaOper { get; set; }
    }
}
